name: Output Github Workflow
on: 
  push:
    branches:
      - 'staging'
      - 'master'
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJSON(github) }}"
